use_frameworks!

platform :ios, '13.0'

target 'ZLForm_Example' do
  pod 'ZLForm', :path => '../'
  pod 'SnapKit'
  target 'ZLForm_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
